CREATE DATABASE IF NOT EXISTS fivem_admin;
USE fivem_admin;

CREATE TABLE IF NOT EXISTS users (
  discord_id VARCHAR(32) PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  role ENUM('GOD','HEAD_ADMIN','ADMIN','TRIAL_ADMIN','HEAD_MOD','MOD','TRIAL_MOD','SENIOR_STAFF','STAFF','TRIALL_STAFF','OWNER','MODERATOR') NOT NULL DEFAULT 'MODERATOR',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
