CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  admin VARCHAR(64) NOT NULL,
  action VARCHAR(64) NOT NULL,
  target_player VARCHAR(64),
  details TEXT
);
